services:
  - type: web
    name: aksaratek
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Aksara Karya"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: aksaratek
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
